/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import BatchActions from "../redux/actions/BatchActions";
import StudentActions from "../redux/actions/StudentActions";
import ProfessorActions from "../redux/actions/ProfessorActions";

// END IMPORT ACTIONS

/** APIs

* actionsBatch.create
*	@description CRUD ACTION create
*
* actionsBatch.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsBatch.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsStudent.findBybatch
*	@description CRUD ACTION findBybatch
*	@param Objectid key - Id of model to search for
*
* actionsProfessor.findBy_batch
*	@description CRUD ACTION findBy_batch
*	@param Objectid key - Id of model to search for
*
* actionsBatch.list
*	@description CRUD ACTION list
*

**/

class BatchEdit extends Component {
  // Init batch
  constructor(props) {
    super(props);
    this.state = {
      batch: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsBatch.loadBatch(this.props.match.params.id);
      this.props.actionsProfessor.findBy_batch(this.props.match.params.id);
      this.props.actionsStudent.findBybatch(this.props.match.params.id);
    }
    
    this.props.actionsBatch.loadBatchList();
  }

  // Insert props batch in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      batch: props.batch
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.batch._id) {
      this.props.actionsBatch.saveBatch(this.state.batch).then(data => {
        this.props.history.push("/batchs/");
      });
    } else {
      this.props.actionsBatch.createBatch(this.state.batch).then(data => {
        this.props.history.push("/batchs/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Batch Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="batch"
            label="Batch"
            value={this.state.batch.batch || ""}
            onChange={Utils.handleChange.bind(this, "batch")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m batch_no with batch */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="batch_no">
              Batch_no
            </InputLabel>
            <Select
              value={this.state.batch.batch_no || ""}
              onChange={Utils.handleChangeSelect.bind(this, "batch")}
              inputProps={{
                id: "batch_no",
                name: "batch_no"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listBatch && this.props.listBatch.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with professor */}
          
          <h3>Professor</h3>
          {(!this.props.listProfessor || this.props.listProfessor.length === 0) && 
            <div>No Professor associated</div>
          }
          {this.props.listProfessor &&
            this.props.listProfessor.map((item, i) => {
              return (
                <Link to={"/professors/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with student */}
          
          <h3>Student</h3>
          {(!this.props.listStudent || this.props.listStudent.length === 0) && 
            <div>No Student associated</div>
          }
          {this.props.listStudent &&
            this.props.listStudent.map((item, i) => {
              return (
                <Link to={"/students/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/batchs/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsBatch: bindActionCreators(BatchActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
  };
};

// Validate types
BatchEdit.propTypes = { 
  actionsBatch: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
  actionsProfessor: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    batch: state.BatchEditReducer.batch,
    listBatch: state.BatchEditReducer.listBatch,
    listProfessor: state.BatchEditReducer.listProfessor,
    listStudent: state.BatchEditReducer.listStudent
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BatchEdit);
