/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";

// Custom Actions


// START IMPORT ACTIONS
import BranchActions from "../redux/actions/BranchActions";
import StudentActions from "../redux/actions/StudentActions";
import ResultActions from "../redux/actions/ResultActions";
import SubjectActions from "../redux/actions/SubjectActions";
import SemesterActions from "../redux/actions/SemesterActions";

// END IMPORT ACTIONS

/** APIs

* actionsBranch.create
*	@description CRUD ACTION create
*
* actionsBranch.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsBranch.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsStudent.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsResult.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsSubject.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsSemester.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*

**/

class BranchEdit extends Component {
  // Init branch
  constructor(props) {
    super(props);
    this.state = {
      branch: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsBranch.loadBranch(this.props.match.params.id);
      this.props.actionsSemester.findBybranch(this.props.match.params.id);
      this.props.actionsSubject.findBybranch(this.props.match.params.id);
      this.props.actionsResult.findBybranch(this.props.match.params.id);
      this.props.actionsStudent.findBybranch(this.props.match.params.id);
    }
    
  }

  // Insert props branch in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      branch: props.branch
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.branch._id) {
      this.props.actionsBranch.saveBranch(this.state.branch).then(data => {
        this.props.history.push("/branchs/");
      });
    } else {
      this.props.actionsBranch.createBranch(this.state.branch).then(data => {
        this.props.history.push("/branchs/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Branch Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="name"
            label="Name"
            value={this.state.branch.name || ""}
            onChange={Utils.handleChange.bind(this, "branch")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with semester */}
          
          <h3>Semester</h3>
          {(!this.props.listSemester || this.props.listSemester.length === 0) && 
            <div>No Semester associated</div>
          }
          {this.props.listSemester &&
            this.props.listSemester.map((item, i) => {
              return (
                <Link to={"/semesters/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with subject */}
          
          <h3>Subject</h3>
          {(!this.props.listSubject || this.props.listSubject.length === 0) && 
            <div>No Subject associated</div>
          }
          {this.props.listSubject &&
            this.props.listSubject.map((item, i) => {
              return (
                <Link to={"/subjects/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with result */}
          
          <h3>Result</h3>
          {(!this.props.listResult || this.props.listResult.length === 0) && 
            <div>No Result associated</div>
          }
          {this.props.listResult &&
            this.props.listResult.map((item, i) => {
              return (
                <Link to={"/results/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with student */}
          
          <h3>Student</h3>
          {(!this.props.listStudent || this.props.listStudent.length === 0) && 
            <div>No Student associated</div>
          }
          {this.props.listStudent &&
            this.props.listStudent.map((item, i) => {
              return (
                <Link to={"/students/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/branchs/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsBranch: bindActionCreators(BranchActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsResult: bindActionCreators(ResultActions, dispatch),
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
  };
};

// Validate types
BranchEdit.propTypes = { 
  actionsBranch: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
  actionsResult: PropTypes.object.isRequired,
  actionsSubject: PropTypes.object.isRequired,
  actionsSemester: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    branch: state.BranchEditReducer.branch,
    listSemester: state.BranchEditReducer.listSemester,
    listSubject: state.BranchEditReducer.listSubject,
    listResult: state.BranchEditReducer.listResult,
    listStudent: state.BranchEditReducer.listStudent
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BranchEdit);
