/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import StudentActions from "../redux/actions/StudentActions";
import ResultActions from "../redux/actions/ResultActions";
import ProfessorActions from "../redux/actions/ProfessorActions";
import BatchActions from "../redux/actions/BatchActions";
import SubjectActions from "../redux/actions/SubjectActions";
import SemesterActions from "../redux/actions/SemesterActions";
import BranchActions from "../redux/actions/BranchActions";

// END IMPORT ACTIONS

/** APIs

* actionsStudent.create
*	@description CRUD ACTION create
*
* actionsStudent.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsStudent.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsResult.list
*	@description CRUD ACTION list
*
* actionsProfessor.list
*	@description CRUD ACTION list
*
* actionsBatch.list
*	@description CRUD ACTION list
*
* actionsSubject.list
*	@description CRUD ACTION list
*
* actionsSemester.list
*	@description CRUD ACTION list
*
* actionsBranch.list
*	@description CRUD ACTION list
*
* actionsProfessor.findBy_student
*	@description CRUD ACTION findBy_student
*	@param Objectid key - Id of model to search for
*
* actionsResult.findBystudent
*	@description CRUD ACTION findBystudent
*	@param Objectid key - Id of model to search for
*

**/

class StudentEdit extends Component {
  // Init student
  constructor(props) {
    super(props);
    this.state = {
      student: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsStudent.loadStudent(this.props.match.params.id);
      this.props.actionsProfessor.findBy_student(this.props.match.params.id);
      this.props.actionsResult.findBystudent(this.props.match.params.id);
    }
    
    this.props.actionsResult.loadResultList();
    this.props.actionsSubject.loadSubjectList();
    this.props.actionsProfessor.loadProfessorList();
    this.props.actionsBatch.loadBatchList();
    this.props.actionsBranch.loadBranchList();
    this.props.actionsSemester.loadSemesterList();
  }

  // Insert props student in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      student: props.student
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.student._id) {
      this.props.actionsStudent.saveStudent(this.state.student).then(data => {
        this.props.history.push("/students/");
      });
    } else {
      this.props.actionsStudent.createStudent(this.state.student).then(data => {
        this.props.history.push("/students/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Student Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Address"
            label="Address"
            value={this.state.student.Address || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Birthdate"
            label="Birthdate"
            value={this.state.student.Birthdate || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Branch"
            label="Branch"
            value={this.state.student.Branch || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Gender"
            label="Gender"
            value={this.state.student.Gender || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Name"
            label="Name"
            value={this.state.student.Name || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Phonenumer"
            label="Phonenumer"
            value={this.state.student.Phonenumer || ""}
            onChange={Utils.handleChange.bind(this, "student")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m _result with result */}
          
          <FormControl fullWidth className="mb-20" required
              {...(!this.state.student._result && !this.state.student._result
                ? { error: true }
                : {})}>
            <InputLabel shrink htmlFor="_result">
              _result
            </InputLabel>
            <Select
              value={this.state.student._result || ""}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              inputProps={{
                id: "_result",
                name: "_result"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listResult && this.props.listResult.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation 1:m _subject with subject */}
          
          <FormControl fullWidth className="mb-20" required
              {...(!this.state.student._subject && !this.state.student._subject
                ? { error: true }
                : {})}>
            <InputLabel shrink htmlFor="_subject">
              _subject
            </InputLabel>
            <Select
              value={this.state.student._subject || ""}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              inputProps={{
                id: "_subject",
                name: "_subject"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listSubject && this.props.listSubject.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation m:m _teacher with professor */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="_teacher">_teacher</InputLabel>
            <Select
              multiple
              value={this.state.student._teacher || []}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              input={<Input id="_teacher" name="_teacher" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listProfessor && this.props.listProfessor.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.student._teacher &&
                      this.state.student._teacher.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m batch with batch */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="batch">Batch</InputLabel>
            <Select
              multiple
              value={this.state.student.batch || []}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              input={<Input id="batch" name="batch" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listBatch && this.props.listBatch.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.student.batch &&
                      this.state.student.batch.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m branch with branch */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="branch">Branch</InputLabel>
            <Select
              multiple
              value={this.state.student.branch || []}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              input={<Input id="branch" name="branch" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listBranch && this.props.listBranch.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.student.branch &&
                      this.state.student.branch.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation 1:m semester with semester */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="semester">
              Semester
            </InputLabel>
            <Select
              value={this.state.student.semester || ""}
              onChange={Utils.handleChangeSelect.bind(this, "student")}
              inputProps={{
                id: "semester",
                name: "semester"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listSemester && this.props.listSemester.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with professor */}
          
          <h3>Professor</h3>
          {(!this.props.listProfessor || this.props.listProfessor.length === 0) && 
            <div>No Professor associated</div>
          }
          {this.props.listProfessor &&
            this.props.listProfessor.map((item, i) => {
              return (
                <Link to={"/professors/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with result */}
          
          <h3>Result</h3>
          {(!this.props.listResult || this.props.listResult.length === 0) && 
            <div>No Result associated</div>
          }
          {this.props.listResult &&
            this.props.listResult.map((item, i) => {
              return (
                <Link to={"/results/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/students/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsResult: bindActionCreators(ResultActions, dispatch),
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
    actionsBatch: bindActionCreators(BatchActions, dispatch),
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
    actionsBranch: bindActionCreators(BranchActions, dispatch),
  };
};

// Validate types
StudentEdit.propTypes = { 
  actionsStudent: PropTypes.object.isRequired,
  actionsResult: PropTypes.object.isRequired,
  actionsProfessor: PropTypes.object.isRequired,
  actionsBatch: PropTypes.object.isRequired,
  actionsSubject: PropTypes.object.isRequired,
  actionsSemester: PropTypes.object.isRequired,
  actionsBranch: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    student: state.StudentEditReducer.student,
    listResult: state.StudentEditReducer.listResult,
    listSubject: state.StudentEditReducer.listSubject,
    listProfessor: state.StudentEditReducer.listProfessor,
    listBatch: state.StudentEditReducer.listBatch,
    listBranch: state.StudentEditReducer.listBranch,
    listSemester: state.StudentEditReducer.listSemester,
    listProfessor: state.StudentEditReducer.listProfessor,
    listResult: state.StudentEditReducer.listResult
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(StudentEdit);
