/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import SubjectActions from "../redux/actions/SubjectActions";
import StudentActions from "../redux/actions/StudentActions";
import ProfessorActions from "../redux/actions/ProfessorActions";
import BranchActions from "../redux/actions/BranchActions";
import SemesterActions from "../redux/actions/SemesterActions";

// END IMPORT ACTIONS

/** APIs

* actionsSubject.create
*	@description CRUD ACTION create
*
* actionsSubject.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsSubject.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsStudent.findBy_subject
*	@description CRUD ACTION findBy_subject
*	@param Objectid key - Id of model to search for
*
* actionsProfessor.findBy_subject
*	@description CRUD ACTION findBy_subject
*	@param Objectid key - Id of model to search for
*
* actionsBranch.list
*	@description CRUD ACTION list
*
* actionsSemester.list
*	@description CRUD ACTION list
*
* actionsProfessor.list
*	@description CRUD ACTION list
*
* actionsSemester.findBysubject
*	@description CRUD ACTION findBysubject
*	@param Objectid key - Id of model to search for
*

**/

class SubjectEdit extends Component {
  // Init subject
  constructor(props) {
    super(props);
    this.state = {
      subject: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsSubject.loadSubject(this.props.match.params.id);
      this.props.actionsStudent.findBy_subject(this.props.match.params.id);
      this.props.actionsProfessor.findBy_subject(this.props.match.params.id);
      this.props.actionsSemester.findBysubject(this.props.match.params.id);
    }
    
    this.props.actionsBranch.loadBranchList();
    this.props.actionsProfessor.loadProfessorList();
    this.props.actionsSemester.loadSemesterList();
  }

  // Insert props subject in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      subject: props.subject
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.subject._id) {
      this.props.actionsSubject.saveSubject(this.state.subject).then(data => {
        this.props.history.push("/subjects/");
      });
    } else {
      this.props.actionsSubject.createSubject(this.state.subject).then(data => {
        this.props.history.push("/subjects/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Subject Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="name"
            label="Name"
            value={this.state.subject.name || ""}
            onChange={Utils.handleChange.bind(this, "subject")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="sub_id"
            label="Sub_id"
            value={this.state.subject.sub_id || ""}
            onChange={Utils.handleChange.bind(this, "subject")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m branch with branch */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="branch">Branch</InputLabel>
            <Select
              multiple
              value={this.state.subject.branch || []}
              onChange={Utils.handleChangeSelect.bind(this, "subject")}
              input={<Input id="branch" name="branch" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listBranch && this.props.listBranch.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.subject.branch &&
                      this.state.subject.branch.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m professor with professor */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="professor">Professor</InputLabel>
            <Select
              multiple
              value={this.state.subject.professor || []}
              onChange={Utils.handleChangeSelect.bind(this, "subject")}
              input={<Input id="professor" name="professor" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listProfessor && this.props.listProfessor.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.subject.professor &&
                      this.state.subject.professor.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m semester with semester */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="semester">Semester</InputLabel>
            <Select
              multiple
              value={this.state.subject.semester || []}
              onChange={Utils.handleChangeSelect.bind(this, "subject")}
              input={<Input id="semester" name="semester" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listSemester && this.props.listSemester.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.subject.semester &&
                      this.state.subject.semester.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with student */}
          
          <h3>Student</h3>
          {(!this.props.listStudent || this.props.listStudent.length === 0) && 
            <div>No Student associated</div>
          }
          {this.props.listStudent &&
            this.props.listStudent.map((item, i) => {
              return (
                <Link to={"/students/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with professor */}
          
          <h3>Professor</h3>
          {(!this.props.listProfessor || this.props.listProfessor.length === 0) && 
            <div>No Professor associated</div>
          }
          {this.props.listProfessor &&
            this.props.listProfessor.map((item, i) => {
              return (
                <Link to={"/professors/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with semester */}
          
          <h3>Semester</h3>
          {(!this.props.listSemester || this.props.listSemester.length === 0) && 
            <div>No Semester associated</div>
          }
          {this.props.listSemester &&
            this.props.listSemester.map((item, i) => {
              return (
                <Link to={"/semesters/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/subjects/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
    actionsBranch: bindActionCreators(BranchActions, dispatch),
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
  };
};

// Validate types
SubjectEdit.propTypes = { 
  actionsSubject: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
  actionsProfessor: PropTypes.object.isRequired,
  actionsBranch: PropTypes.object.isRequired,
  actionsSemester: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    subject: state.SubjectEditReducer.subject,
    listBranch: state.SubjectEditReducer.listBranch,
    listProfessor: state.SubjectEditReducer.listProfessor,
    listSemester: state.SubjectEditReducer.listSemester,
    listStudent: state.SubjectEditReducer.listStudent,
    listProfessor: state.SubjectEditReducer.listProfessor,
    listSemester: state.SubjectEditReducer.listSemester
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SubjectEdit);
